# This is a template configuration file for your data analysis tool.
# Use this file as a starting point by copying and editing it to fit your
# requirements. The configuration file follows TOML syntax. For more details,
# visit: https://toml.io.
#
# IMPORTANT: Remove all comments (lines starting with '#') before using this
# configuration.

[tool]
# General information about your tool.
authors = [
    "Author 1 <author1@email.com>",
    "Author 2 <author2@email.com>"
]  # List of authors and their contact information.
version = "v0.0.1"  # Semantic version of the tool.
summary = "A brief description of what this tool does."  # Short overview.
title = "A catchy title for the tool (optional)"  # Optional title for flair.
description = """
A detailed description of the tool's purpose and functionality. This section
supports multi-line text for extensive details.
"""  # Extended multi-line description.

[tool.run]
# Defines how your tool is executed. This section specifies the command to
# run, such as a script, compiled binary, or Jupyter notebook.
command = echo hello world  # Command to execute the tool.
# The specified command will receive a single JSON input containing all input
# parameters. Ensure your script processes this JSON file. Refer to the
# example script for guidance.
dependencies = ["python=3.13", "ffmpeg"]  # Conda-forge packages needed.

[tool.build]
# Configuration for building the tool.
dependencies = ["python=3.13", "mamba"]  # Optional build-specific deps.
# NOTE: If a 'build.sh' script is provided, it will be executed during build.
